In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [7]:
dep_lab = pd.read_csv('Dataset/problem_10/dependency_labels.csv', encoding='latin1')
dep_lab.head()

,dep_id,application_id,library,version,is_risky,risk_type,severity,explanation
0,DEP-0001,APP-001,micrometer-core,3.0.10,True,VULNERABLE_DEPENDENCY,MEDIUM,Library micrometer-core:3.0.10 has CVE-2026-10...
1,DEP-0002,APP-001,sqlalchemy,5.13.5,True,VULNERABLE_DEPENDENCY,LOW,Library sqlalchemy:5.13.5 has CVE-2024-1183 (C...
2,DEP-0003,APP-001,netty-all,2.7.4,True,VULNERABLE_DEPENDENCY,MEDIUM,Library netty-all:2.7.4 has CVE-2024-1163 (CVS...
3,DEP-0004,APP-001,json-iterator,2.3.2,True,VULNERABLE_DEPENDENCY,MEDIUM,Library json-iterator:2.3.2 has CVE-2022-1083 ...
4,DEP-0005,APP-001,log4j-api,5.1.3,True,VULNERABLE_DEPENDENCY,MEDIUM,Library log4j-api:5.1.3 has CVE-2022-1041 (CVS...

In [8]:
dep_lab.columns

Index(['dep_id', 'application_id', 'library', 'version', 'is_risky',
       'risk_type', 'severity', 'explanation'],
      dtype='object')

In [9]:
sbom_dep = pd.read_csv('Dataset/problem_10/sbom_dependencies.csv', encoding='latin1')
sbom_dep.head()

,dep_id,application_id,application_name,library,version,license,dependency_type,last_updated,transitive_deps
0,DEP-0001,APP-001,CustomerPortal,micrometer-core,3.0.10,Apache-2.0,direct,2025-01-30,tomcat-embed-core:2.4.0
1,DEP-0002,APP-001,CustomerPortal,sqlalchemy,5.13.5,ISC,direct,2022-03-18,NaN
2,DEP-0003,APP-001,CustomerPortal,netty-all,2.7.4,Unlicense,direct,2025-05-01,assertj-core:2.1.1
3,DEP-0004,APP-001,CustomerPortal,json-iterator,2.3.2,BSD-2-Clause,direct,2024-12-30,disruptor:3.1.0
4,DEP-0005,APP-001,CustomerPortal,log4j-api,5.1.3,Apache-2.0,direct,2025-07-11,eslint:3.4.1

In [10]:
sbom_dep.columns

Index(['dep_id', 'application_id', 'application_name', 'library', 'version',
       'license', 'dependency_type', 'last_updated', 'transitive_deps'],
      dtype='object')

In [13]:
apps = pd.read_json('Dataset/problem_10/applications.json')
apps.head()

,app_id,name,language,criticality,license_model,business_owner,department,deployment
0,APP-001,CustomerPortal,Java,HIGH,proprietary,Sarah Chen,Engineering,cloud
1,APP-002,PaymentService,Java,CRITICAL,proprietary,Mike Torres,Finance,cloud
2,APP-003,InternalAPI,Python,MEDIUM,proprietary,Priya Patel,Engineering,on-prem
3,APP-004,HRPortal,Python,HIGH,proprietary,James Wilson,HR,cloud
4,APP-005,AnalyticsDashboard,JavaScript,MEDIUM,proprietary,Lisa Wang,Data,cloud

In [14]:
licence = pd.read_json('Dataset/problem_10/license_rules.json')
licence.head()

,license,spdx,risk_level,compatible_with_proprietary,viral,notes
0,MIT,MIT,LOW,True,False,Permissive; no restrictions on use
1,Apache-2.0,Apache-2.0,LOW,True,False,Permissive; patent grant included
2,BSD-2-Clause,BSD-2-Clause,LOW,True,False,Permissive; minimal restrictions
3,BSD-3-Clause,BSD-3-Clause,LOW,True,False,Permissive; no endorsement clause
4,ISC,ISC,LOW,True,False,Permissive; simplified BSD

In [15]:
transitive = pd.read_json('Dataset/problem_10/transitive_dependencies.json')
transitive.head()

,parent_library,parent_version,child_library,child_version,application_id
0,micrometer-core,3.0.10,tomcat-embed-core,2.4.0,APP-001
1,netty-all,2.7.4,assertj-core,2.1.1,APP-001
2,json-iterator,2.3.2,disruptor,3.1.0,APP-001
3,log4j-api,5.1.3,eslint,3.4.1,APP-001
4,lombok,4.1.2,jackson-core,2.2.2,APP-001

In [16]:
transitive.columns

Index(['parent_library', 'parent_version', 'child_library', 'child_version',
       'application_id'],
      dtype='object')

In [17]:
vulnerability = pd.read_json('Dataset/problem_10/vulnerability_db.json')
vulnerability.head()

,cve_id,library,affected_versions,fixed_version,cvss_score,severity,exploitability,description,patch_available,published_date
0,CVE-2023-1000,gomock,"[3.2.0, 3.5.0]",3.5.0,1.8,LOW,MEDIUM,Cross-site scripting (XSS) in template renderi...,True,2023-11-08
1,CVE-2026-1001,gomock,"[5.3.0, 5.4.0]",None,7.3,HIGH,MEDIUM,SQL injection through improperly sanitized use...,False,2026-04-14
2,CVE-2023-1002,lombok,"[4.6.0, 4.7.0]",4.10.0,9.9,CRITICAL,MEDIUM,Open redirect vulnerability in URL handling,True,2023-10-03
3,CVE-2025-1003,jackson-databind,"[4.1.0, 4.2.0]",None,6.9,MEDIUM,LOW,Man-in-the-middle due to improper TLS certific...,False,2025-11-02
4,CVE-2024-1004,werkzeug,"[1.8.0, 1.10.0]",None,5.6,MEDIUM,HIGH,Man-in-the-middle due to improper TLS certific...,False,2024-03-21